version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env.docker
    ports:
      - 5000:5000
    volumes:
      - ./logs/:/root/logs/
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - app-tier

  database:
    image: mysql:8.0.34-debian
    container_name: database
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DB: school
      PGDATA: /data/mysql
    volumes:
      - .docker/data/mysql:/data/mysql
    ports:
      - "5432:5432"
    networks:
      - app-tier
    restart: always

  redis:
    image: redis:7.0-alpine
    container_name: redis
    env_file:
      - .env.docker
    command: redis-server --save 60 1 --requirepass $REDIS_PASSWORD
    volumes:
      - .docker/data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - app-tier
    restart: always
networks:
  app-tier:
    driver: bridge
    name: app-tier
